### ISSUE TITLE
[proposal] Refactor the 'Value' type

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#136]
**1.Background:**

The objects stored in the operand stack, local variables and global state are finite field elements which are organized as a 'Value' type. 

```
pub enum Value<F: FieldExt> {
    Invalid,
    Constant(FConstant<F>),
    Variable(FVariable<F>),
    Reference(Ref),
}
```
This 'Value' type is defined at the very beginning. As we are implementing or will implement reference, struct, and vector next, this design is no longer sufficient for our needs. I would like to throw out the question here and suggest possible solutions for discussion.

**2.Two options**

**Option#1** Expand on what's already there, similar to the ValueImpl in the community Move vm

```
pub enum Value<F: FieldExt> {
    Invalid,
    /*Constant(FConstant<F>),*/ // do we really need to distinguish constant and variable?
    /*Variable(FVariable<F>), */ // replace with each primitive value
    U8(F),
    U64(F),
    U128(F),
    Bool(F),
    Address(F),
    Container(Container<F>),
    ContainerRef(ContainerRef),
    IndexedRef(IndexedRef), // point to an element in a container
}

enum Container<F: FieldExt> {
    Locals(Rc<RefCell<Vec<Value<F>>>>),
    Struct(Rc<RefCell<Vec<Value<F>>>>),
}

enum ContainerRef<F: FieldExt> {
    Local(Container<F>),  // in the frame
    Global(Container<F>),  // in the global state
}

struct IndexedRef<F: FieldExt> {
    idx: usize,
    container_ref: ContainerRef<F>,
}
```

for example, borrow to locals can be expressed as 

```
Value::IndexedRef(IndexedRef {
                container_ref: ContainerRef::Local(Container::Locals(Rc::clone(&locals))), 
                idx,
            })),
```

**Option#2** Instead of storing finite field elements on stack/locals/globals, store native Move value.

The reason for using the finite field on the stack/locals is to allow zkmove-lite to generate the circuit directly. We also hope the VM can be more zk friendly and more efficiency on generating proof. This is why we didn't reuse community Move VM directly.

But it seem using native Move value on stack/locals doesn't impact the performance of proof generation. Because we can transform native Move value to finite field just in the rw_operations which is generated when the bytecode is interpreted. What affects performance the most is hash and signature, we will use zk friendly algorithm.

This is a relatively big change. I don't expect to make a decision right now. I am inclined to continue Option#1 and for option#2 to discuss further.

**Comment by markvanvliet** [comment]
I'll weigh in here - I initially attempted to mimic the pattern in the community Move repo where references not only hold indices, but also references to their containers. I assumed this would be fine as it would be extensible to vectors and structs later on, but I ran into some issues.

As the RWOperations were constructed while the program executed, it would contain copies of the references in question, used in the program. This is initially fine, but it means that once the circuit is constructed, it creates RWOperations that hold the actual references; meaning that if state is mutated throughout the program, the circuit no longer matches the lookup tables that are generated, and constraints will not satisfy. It was very difficult to work around this without incurring extra cost (such as snapshotting the container state when the RWOperations were generated), or not being true to the actual program execution (by replacing refs with their actual value).

I am in favor of option zkmove/zkmove#141 for now too, as we should not try to optimize too heavily for now. We can reasonably leave it for later work, and I would like to reason more about how we can optimize efficiently in the future, but I think it is sensible to direct our focus towards shipping first, and making the heavier modifications later. Potential tech debt aside, it's always easier to reason about mutating a working product (since you can get more direct feedback of your modifications), rather than attempting to reason through optimal designs initially and then discovering later that it could have been done better.

So, let's stick to option zkmove/zkmove#141, but let's either make sure we don't run into the same issue as mentioned above, or maybe we can reason about a good way to mitigate it - however I'd vote for the most straightforward option for now!

**Comment by guangyuz** [comment]
> As the RWOperations were constructed while the program executed, it would contain copies of the references in question, used in the program. This is initially fine, but it means that once the circuit is constructed, it creates RWOperations that hold the actual references; meaning that if state is mutated throughout the program, the circuit no longer matches the lookup tables that are generated, and constraints will not satisfy. It was very difficult to work around this without incurring extra cost (such as snapshotting the container state when the RWOperations were generated), or not being true to the actual program execution (by replacing refs with their actual value).

I would like RWOperations NOT hold the actual references, but hold their actual value. Then the circuit will be decoupled from the execution. (I see that you seem to be doing that already). I would suggest to add more rw type, then the constraints will be more easy to add.

1. For the interpreter side, implement the pattern in the community Move repo where references not only hold indices, but also references to their containers. (described in option#1)

2. generate rw_operation with new rw type
```
pub enum RW {
    READ = 0,
    WRITE,
    MUT_REF,
    IMM_REF,
}
```
for mut_borrow, will generate below rw_operation:
```
        LocalsOp {
                    call_index,
                    index,
                    value: v.clone(),
                    rw: RW::MUT_REF,  // new added rw type
                    gc: rw_operations.len(),
        };
```

3. in locals_op_chip, add below constrains:

for ops with same call_index/index, 
i) there is only one MUT_REF at most
ii) all the IMM_REF have equal value
...
